/* paper-data.js : auto-generated from the course-paper summary.md files.
   window.__PAPER_SUMMARIES[slug] = { title, body }. Edit the source summary.md
   and regenerate, or edit here directly. */
window.__PAPER_SUMMARIES = {
  "treasury-risk-triangle": {
    "title": "The Treasury Risk Triangle",
    "body": "Risk attribution for tradeable fixed-income vehicles usually depends on either internal duration models or proprietary options-implied volatility series such as the MOVE index. This paper builds a fully public-data alternative. It decomposes the daily returns of fourteen liquid instruments (Treasury ETFs and futures) onto three observable risk axes: a model-implied real-rate change, a model-fitted inflation-compensation change, and a residualized nominal-curve shape factor, all reconstructed from public Federal Reserve releases. Using daily data from 2007 to 2025 and per-asset HAC regressions with Romano-Wolf family-wise error control across forty-two asset-by-component cells, the paper tests whether the three axes are separable and whether each instrument's loadings line up with its known duration, inflation-hedge, and curve-geometry profile. The components are statistically separable, twenty-six of forty-two cells survive family-wise control with the predicted signs, and the magnitude ordering matches the locked priors at a rank correlation above 0.92 for every component. Signs stay stable across six robustness specifications, preserving 175 of 180 strong-cell signs. The result is a transparent, reproducible benchmark that practitioners can rebuild daily without proprietary volatility inputs."
  },
  "bonds-stop-hedging-stocks": {
    "title": "Why Did Bonds Stop Hedging Stocks?",
    "body": "After two decades in which long-duration US Treasuries reliably cushioned equity losses, the stock-bond hedge broke down after 2021: the average monthly correlation rose from about −0.34 to roughly zero, leaving a standard 60/40 portfolio with much less protection. The common explanation blames inflation and the vulnerability of nominal bonds. This paper asks whether that is the whole story. Using daily US data from 2003 through 2025, twenty-three equity baskets, and three observable rate proxies that separate real-rate, inflation, and short-rate news, it estimates how the equity response to each type of news changed after 2021. The central finding is a sign reversal in how stocks react to real-rate news: growth-sensitive rate moves that once supported equities began to hurt them, consistent with a market that now reads strong data as a signal of tighter policy. A time-varying decomposition attributes about 78 percent of the correlation shift to this real-rate channel and only about 21 percent to inflation, and the effect strengthens once the 2022 tightening cycle is under way. The practical lesson for allocators is that long Treasuries are conditional diversifiers, not unconditional hedges, and their protection depends on the perceived policy reaction function."
  },
  "price-of-stagflation-risk": {
    "title": "The Price of Stagflation Risk",
    "body": "Inflation can come from demand or from supply, and a growing literature argues the two should be priced differently by markets. This paper runs a strict, pre-registered test of that idea across the whole US asset surface: nominal Treasuries, TIPS, breakevens, equities, the dollar, commodities, and credit. It splits PCE inflation into demand- and supply-driven components using the Shapiro decomposition, instruments the supply leg with Kanzig's OPEC oil-supply-news shock, and estimates local-projection responses for fifteen assets at four horizons, with family-level multiple-testing control and a bootstrap that respects each asset's effective sample. The headline test, whether the demand and supply prices of risk differ with the predicted sign, fails on both pre-registered criteria: the estimate has the wrong sign and a two-sided p-value of 0.06. The equity leg and the ten-year nominal Treasury both load with the wrong sign and are reported as observed, without reframing. Only the commodity family clears Romano-Wolf significance. The contribution is a disciplined null: under a transparent pre-registration with explicit kill-shot triggers, structural-origin inflation is not, in this sample and under this identification, priced consistently across the cross-asset surface."
  },
  "macro-disagreement-industry-rotation": {
    "title": "Macro Disagreement and Industry Rotation",
    "body": "Does disagreement among professional forecasters about the macroeconomy show up as a priced risk in the stock market, or only as a pattern in which industries rotate? This paper tests both readings on a single pre-registered design. Using Survey of Professional Forecasters dispersion in growth, inflation, and short-rate forecasts from 1981 to 2025, it extracts the surprise component of each disagreement series and asks, first, whether industries respond differently to these surprises, and second, whether the resulting exposures earn a Fama-MacBeth cross-sectional premium across the twelve Ken French industry portfolios. The result is deliberately split. Growth disagreement is clearly linked to a cyclical-industry rotation: durables, retail, business equipment, and other cyclicals load positively, and energy loads negatively. But the implied exposures command no statistically significant risk premium, and that pricing null survives four pre-registered robustness changes, including alternative inflation and rate measures and a pre/post-2009 sample split. The contribution is a clean, reproducible null: forecaster disagreement behaves as a state variable correlated with rotation, not as a separately priced cross-sectional risk factor. The design pre-commits to this distinction so that a null pricing test is reported as a null rather than reframed as supportive."
  },
  "revision-robust-forecasting": {
    "title": "Revision-Robust Real-Time Macroeconomic Forecasting",
    "body": "Most evaluations of macroeconomic forecasting models quietly use final, fully revised data, even though a forecaster in real time only ever sees preliminary releases that are later revised. This paper measures how much that shortcut flatters reported accuracy, using the ALFRED real-time archive of 32 series and a panel of standard and machine-learning forecasting models. The distortion is large and uneven. For GDP growth, moving from a final-data backtest to a genuinely real-time evaluation raises forecast error by about 1.2 RMSFE points, almost entirely because models are trained on first-release rather than revised GDP figures; for core inflation the effect is small, and for the rarely-revised unemployment rate it is negligible. The paper then proposes penalizing a model's sensitivity to the estimated revision covariance and tests it honestly: the method gives competitive GDP nowcasts, but the gain comes mostly from the model architecture, with the revision penalty itself adding value only at the one-quarter-ahead horizon and not for other targets. Conformal prediction intervals built on real-time errors are much wider than their final-data counterparts. The practical message is that final-data backtests can be misleading about which methods actually work in real time, especially for GDP."
  },
  "denied-mortgage-applicants": {
    "title": "How Risky Are Denied Mortgage Applicants?",
    "body": "Lenders observe repayment only for the loans they approve, so the default risk of rejected applicants is never directly seen. This missing counterfactual matters for judging whether mortgage denial standards are too strict. Using the near-universe of US mortgage applications from HMDA linked at the risk-cell level to Freddie Mac loan performance from 2018 to 2022, excluding the COVID-distorted 2019 cohort, this paper puts partial-identification bounds on the default rate that denied applicants would have had if approved. Rather than chase a narrow point estimate, it asks a robustness question: how much hidden adverse selection would it take to justify current denial rates? The answer is a lot. Denied applicants would need to be at least ten percentage points riskier than observably identical approved borrowers, roughly five times the default gradient actually seen across denial-rate quintiles, before a welfare-maximizing policy would stop expanding lending. The analysis also shows that the binding source of uncertainty is not adverse selection but transport, the gap between Freddie-observed and population default rates. That is a constructive finding, because transport uncertainty can be reduced with richer data linkage, whereas the true degree of adverse selection can never be observed."
  }
};
